### ISSUE TITLE
Is there a way to have the correction ?

### ISSUE THREAD

**Issue by lironsam** [COMPSCI290-S2016/Group2_ShapeGoogle#1]
Hi,

I would like to know if there is a way to have the correction for shape retrieval ?

Thank you

**Comment by ctralie** [comment]
Hello,
Thank you for your interest in my code!  Since this was for a class assignment, to preserve its integrity for future use, I can't post the solutions publicly.  But I'm happy to send you the solutions in a private correspondence.
All the best,
Chris
